task_name: election
label_name: label  # This option makes multi-label inferencing become valid. 

train_data_path: ./synthetic_election_train.json
val_data_path: ./synthetic_election_val.json
test_data_path: ./synthetic_election_test.json
prompt_templates:
  observations:
    multi_content: |
      Here's a tweet from a user:
      Tweet: ${text}
      
      This person's voting preference is ${label}.
    
  few_shot_prefix: |
    We have seen some examples:

  initialize_zero_shot:
    system: |-
      You are a social scientist.
      Based on your past experiences, please generate hypotheses that are useful for predicting the US election voting preference of a person. 
      The observation is a tweet from the person.
      
      These hypotheses should identify patterns in the tweet that predict voting preferences of the person.
      Please propose ${num_hypotheses} refined hypotheses and generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      
    user: |-
      Please generate hypotheses that are useful for predicting the US election voting preference of a person based on the tweet.
      Please propose ${num_hypotheses} possible hypotheses.

      Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis]. 

      Proposed hypotheses:

  batched_generation:
    system: |-
      You are a social scientist, you are great at predicting the US election voting preference of a person based on their tweets.
      Given a set of tweets from different people and their voting preferences, we want to generate hypotheses that are useful for predicting the US election voting preference of a person based on the tweet.

      Your task is to identify what patterns or traits show up more in people with each of the voting preferences. Focus on the generalizable insight that can be applied in other contexts. Ignore things that are specific to this dataset. Do not make references to this dataset as they may not be applicable to others.

      Using the given examples, please propose ${num_hypotheses} possible hypothesis pairs.
      When proposing hypotheses, look closely into the given examples and identify specific patterns that occur across the provided tweet examples. 
      The hypotheses should be clear, easy to understand, and have specific details such that one can apply the hypotheses to predict the voting preference of a person based on their tweet.

      Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      The hypotheses should analyze the voting preferences of the people in the tweet examples.

    user: |-
      We have seen some tweets and their voting preferences:
      ${observations}
      Please generate hypotheses that are useful for predicting the US election voting preference of a person based on the tweet.
      Propose ${num_hypotheses} possible hypotheses. Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      
      When proposing hypotheses, look closely into the given examples and identify specific patterns that occur across the provided tweet examples. 

      Please make sure that the hypotheses are:
      i. clear (i.e., precise, not too wordy, and easy to understand);
      ii. generalizable to novel situations (i.e., they would make sense if applied to other tweets or other contexts);
      iii. empirically plausible (i.e., this is a dimension on which students can vary on);
      iv. usable (i.e., a human equipped with this insight could use it to predict a new person's voting preference based on their tweet in a similar way).

      Proposed hypotheses:

  few_shot_baseline:
    system: |-
      You are a social scientist and want to determine the voting preference of a person based on their tweet.
      You will see a person's tweet,
      and you need to predict the voting preference of the person.
      Give an answer. The answer should be exactly one of the three phrases (Likely Republican Voter, Likely Third-party/Abstain Voter, Likely Democratic Voter).
      You must give your final answer in the format of "Final answer: ANSWER"

    user: |-
      ${few_shot_prefix}${observations}
      Here's a new tweet: 
      Tweet: ${text}
      
      What's the voting preference of this person?
      You must give your final answer in the format of "Final answer: ANSWER".
  
  IO_refine_with_feedback:
    system: |-
      
    user: |-
      Applying your rule to the following inputs does not produce the expected outputs.
      Here's your proposed hypothesis: ${hypothesis_text}
      Below is some examples that you predicted wrong using the hypothesis.
      ${observations}
      Please generate new hypotheses that maps the given inputs to their corresponding outputs.
      Propose ${num_hypotheses} possible hypotheses. Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].

  inference:
    system: |-
      You are a social scientist and want to determine the voting preference of a person based on the person's tweet.
      From past experiences, you learned a pattern. 
      You need to determine whether each of the patterns holds for the current tweet, and also predict the person's voting preference.
      Give an answer. The answer should be one of the three phrases(Likely Republican Voter, Likely Third-party/Abstain Voter, Likely Democratic Voter).
      You must give your final answer in the format of "Final answer: ANSWER"

    user: |-
      Our learned patterns: ${hypothesis}                          
      New tweet:
      Tweet: ${text}

      Given the pattern you learned above, give an answer of the voting preference of this person.
      Think step by step.
      First step: Think about if the pattern can be applied to the tweet.
      Second step: Based on the pattern, what's the voting preference of this person?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.
      
  multiple_hypotheses_inference:
    system: |-
      You are a social scientist and want to determine the voting preference of a person based on the person's tweet.
      From past experiences, you learned some patterns. 
      You need to determine whether each of the patterns holds for the current tweet, and also predict the person's voting preference.
      Give an answer. The answer should be one phrase of the three phrases (Likely Republican Voter, Likely Third-party/Abstain Voter, Likely Democratic Voter).
      Give your final answer in the format of "Final answer: ANSWER"
    user: |-
      Our learned patterns: ${hypotheses}                          
      New tweet:
      Tweet: ${text}

      Given the patterns you learned above, give an answer of the voting preference of this person.
      Think step by step.
      First step: Think about which pattern can be applied to the tweet.
      Second step: Based on the pattern, what's the voting preference of this person?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.
