task_name: shoe

train_data_path: ./shoe_train.json
val_data_path: ./shoe_val.json
test_data_path: ./shoe_test.json
prompt_templates:
  observations:
    multi_content: |
      A customer is ${appearance}. This customer bought a pair of ${label} shoes.
  adaptive_info_prompt:
    multi_content: |
      Pattern ${idx}: ${hypothesis_text}
      ${observations}
  few_shot_prefix: |
    Here are some examples of customers with certain features buying certain products:

  initialize_zero_shot:
    system: |-
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      Based on your past experiences, please generate hypotheses that are useful for predicting the color of the shoes given the appearance of the person.
      The description of a person's appearance includes their gender, height, age, hat color, shirt color, bag color, and bag size.
      
      These hypotheses should identify patterns that you can find in the data. They should also be generalizable to new instances.
      Please propose ${num_hypotheses} refined hypotheses and generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].

    user: |-
      Please generate hypotheses that are useful for predicting what color of shoes a customer will buy based on their appearance.
      Please propose ${num_hypotheses} possible hypotheses.

      Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis]. 

      Proposed hypotheses:
    
  batched_generation:
    system: |-
      You're a helpful assistant. Your task is given as follows:
      Given a set of observations, we want to generate hypotheses that are useful for predicting the color of the shoes given the appearance of the person. 
      Please be concise and keep the hypotheses to be one-sentence long.  
      Please generate them in the format of 
      {1. [hypothesis]. 
      2. [hypothesis].
      ... 
      ${num_hypotheses}. [hypothesis].}
      Only propose ${num_hypotheses} possible hypotheses in total.
      Please make the hypotheses general and applicable to new examples.

    user: |-
      We made some observations:
      ${observations}
      Based on the above observations, generate ${num_hypotheses} hypotheses.
      Please be concise and keep the hypotheses to be one-sentence long.  
      Please generate them in the format of 
      {1. [hypothesis]. 
      2. [hypothesis].
      ... 
      ${num_hypotheses}. [hypothesis].}
      Only propose ${num_hypotheses} possible hypotheses in total.

  few_shot_baseline:
    system: |-
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes. 
      Give your answer for the shoe color recommendation. The answer should be one color word. It has to be one of white, red, orange, green, blue, and black. If you do not have enough information to make a recommendation, you should give the answer "unknown". 
      Give your final answer in the format of "Final answer: [answer]."

    user: |-
      ${few_shot_prefix}${observations}
      New customer: ${appearance} is buying a pair of shoes, the shoes should be which color?
      Answer:

  IO_refine_with_feedback:
    system: |-
      
    user: |-
      Applying your rule to the following inputs does not produce the expected outputs.
      Here's your proposed hypothesis: ${hypothesis_text}
      Below is some examples that you predicted wrong using the hypothesis.
      ${observations}
      Please generate new hypotheses that maps the given inputs to their corresponding outputs.
      Propose ${num_hypotheses} possible hypotheses. Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      
  inference:
    system: |-
      Instruction:
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      From past experiences, you learned some patterns. 
      Now, at each time, you should apply the learned pattern, given below, to a new customer and recommend a shoe color.
      Please give an answer for the shoe color recommendation. 
      Please give your answer with only one color word, which has to be one of white, red, orange, green, blue, and black.
      Please give your final answer in the format of {Final answer: answer}

    user: |-
      Our learned pattern: ${hypothesis}
      New customer: ${appearance} is buying a pair of shoes, the shoes should be which color?
      
      Given the patterns you learned above, give an answer for the shoe color recommendation. 
      Think step by step.
      First step: Consider if the pattern can be applied to this customer.
      Second step: Based on the pattern, what color of shoe should this customer buy?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.

  multiple_hypotheses_inference:
    system: |-
      Instruction:
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      From past experiences, you learned some patterns. 
      Now, at each time, you should apply the learned pattern, given below, to a new customer and recommend a shoe color.
      Please give an answer for the shoe color recommendation. 
      Please give your answer with only one color word, which has to be one of white, red, orange, green, blue, and black.
      Please give your final answer in the format of {Final answer: answer}

    user: |-
      Our learned patterns: ${hypotheses}                          
      New customer: ${appearance} is buying a pair of shoes, the shoes should be which color?

      Given the patterns you learned above, give an answer for the shoe color recommendation. 
      Think step by step.
      First step: Think about which pattern can be applied to this customer.
      Second step: Based on the pattern, what color of shoe should this customer buy?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.

  is_relevant:
    system: |-
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      From past experiences, you learned a pattern. 
      Now, given the appearance of a new customer, you need to determine whether this pattern is relevant or not.
      Please answer "yes" if the pattern is relevant and "no" if the pattern is not relevant.
      Please keep you answer short (1-2 sentences).
      Please give your final answer in the format of {Final answer: answer}.

    user: |-
      Pattern: ${hypothesis}
      New customer: ${appearance}
      Is the given pattern applicable to predict the color of shoe this new customer will buy?

  adaptive_inference:
    system: |-
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      From past experiences, you learned some patterns. 
      For each pattern, you will also see a couple of examples that worked for each pattern.
      Choose a pattern. To do this, look at the examples of each pattern, and see which of the examples the current customer is closest to. Choose the pattern corresponding to that example.
      Give an answer for the shoe color recommendation. 
      The answer should be one word. It has to be one of white, red, orange, green, blue, and black.
      Give your final answer in the following format:
      Reasoning for choosing pattern: reason,
      Chosen pattern: pattern,
      Reasoning for choice of prediction: reason,
      Final Answer: answer

    user: |-
      Here are some previously generated patterns with some example where it predicted correcly what color of shoe the customer bought.
      ${adaptive_info_prompt}
      New customer: ${appearance} is buying a pair of shoes, the shoes should be which color?
      Answer: 

  adaptive_selection:
    system: |-
      You are a shoe salesman and want to recommend shoes to customers. There are white, red, orange, green, blue, and black shoes.
      From past experiences, you learned some patterns. 
      You will see a couple of examples that worked for each pattern.
      Please choose a pattern. To do this, look at the examples of each pattern, and see which of the examples the current customer is closest to. 
      Please choose the pattern corresponding to those examples.
      Please give your final answer in the following format:
      Reasoning for choosing pattern: reason,
      Chosen pattern: pattern <number>.

    user: |-
      Here are some previously generated patterns with some examples where it predicted correcly what color of shoe the customer bought.
      ${adaptive_info_prompt}
      New scenario: ${appearance} is buying a pair of shoes, the shoes should be which color?
      Look at the new customer and compare this scenario with the set of examples associated with each provided pattern. 
      Find the set of examples that is the most similar to the new scenario, pick and repeat the pattern associated with that set of examples.
      Please give your final answer in the following format:
      Reasoning for choosing pattern: reason,
      Chosen pattern: pattern <number>.
