# .github/workflows/publish.yml
name: Publish Python to PyPI

on:
  push:
    tags:
      - "v*.*.*"          # run on every version tag like v0.2.1

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: python -m pip install --upgrade build

      - name: Build wheel and sdist
        run: python -m build        # outputs into dist/

      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish Python distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hypogenic
    permissions:
      id-token: write         # for Trusted Publishing

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Sign and attach dists to GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign distributions with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: |
            dist/*.tar.gz
            dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" --repo "${{ github.repository }}" --notes ""

      - name: Upload signed dists to Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.ref_name }}" dist/** --repo "${{ github.repository }}"
